---
name: iOS Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15
      - name: Install xpretty util command
        run: |
          gem install xcpretty
      - name: Build CoreML Project
        run: |
          xcodebuild build-for-testing \
          -project SentimentAnalysis/SentimentAnalysis.xcodeproj \
          -scheme SentimentAnalysis \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
          -derivedDataPath build | xcpretty
      - name: Build Live Camera Project
        run: |
          xcodebuild build-for-testing \
          -project CameraLiveCaptureTesting/CameraLiveCaptureTesting.xcodeproj \
          -scheme CameraLiveCaptureTesting \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
          -derivedDataPath build | xcpretty
